### ISSUE TITLE
Contributon Preview

### ISSUE THREAD

**Issue by songyiYu** [flutter-moum/flutter-moum#1]
# 컨트리뷰톤 프리뷰
> 컨트리뷰톤 발대식 전 간단한 내용들을 공유합니다.

## 플러터 전반적인 이해 (참고용)
1. [플러터는 왜 혁명적인가](https://medium.com/@dan_kim/%EB%B2%88%EC%97%AD-flutter%EB%8A%94-%EC%99%9C-%ED%98%81%EB%AA%85%EC%A0%81%EC%9D%B8%EA%B0%80-967c1dfcc5a9)
2. 플러터 환경 설정 한 후, New Project 만들고 build 해보기 (Counter 예제)
3. 플러터 이해하기 - https://proandroiddev.com/flutter-from-zero-to-comfortable-6b1d6b2d20e   
4. 보충 - [기존 안드로이드 개발자의 플러터 이해도 높이기](https://flutter.dev/docs/get-started/flutter-for/android-devs), [기존 아이폰 개발자의 플러터 이해도 높이기](https://flutter.dev/docs/get-started/flutter-for/ios-devs)
5. 심화 - [Flutter 강좌 with Provider](https://www.youtube.com/watch?v=kB3tTZhnJIg&t=808s) - 플러터를 어느정도 하고 난 뒤 보면 굉장히 좋은 강좌입니다. 상태관리 패턴과 함께 설명해주는 강좌입니다.
6. 번외 - [이주의 플러터 위젯](https://www.youtube.com/playlist?list=PLOU2XLYxmsIL0pH0zWe_ZOHgGhZ7UasUE) - 매주 플러터팀에서 얼마나 다양하고 유용한 위젯들을 만드는지 볼 수 있습니다.

## @ Required
[Plugin 기초 example 따라하기](https://flutter.dev/docs/development/platform-integration/platform-channels) - 따라 한 후, 에뮬레이터나 시뮬레이터 화면을 캡쳐하여 이슈에 올려주세요.

## 배포 (https://pub.dev/)
플러그인이 개발이 되면 pub.dev 에 배포가 될텐데요, 여기가 플러터의 모든 플러그인이 모여 있는 곳이고 이곳에 배포가 되면 다른 개발자들이 사용할 수 있는 상태가 됩니다. 
https://pub.dev/ 는 즐겨찾기로 해두시고 유명한 플러그인들이나 잘 관리가 되고 있는 플러그인들을 한 번 보시면 여러모로 좋습니다. 혹은 본인이 잘 아는 분야의 플러그인들은 코드도 직접 뜯어보시면 도움이 됩니다. (대개 github 주소도 함께 나와있습니다.) SharedPreferences 같은 플러그인들을 한번 뜯어보시는것 추천!

## Git의 이해
1. [좋은 git 커밋 메시지를 작성하기 위한 7가지 약속](https://meetup.toast.com/posts/106) - 반드시 지키라는건 아니구요. 적당히 참고해주시면 됩니다.
2. [지옥에서 온 git](https://www.youtube.com/playlist?list=PLuHgQVnccGMA8iwZwrGyNXCGy2LAAsTXk) - 이 동영상 강의 좋습니다. 이미 깃에 대해 알고 계신 분들도 들으면 좋은 강의
3. [깃허브로 취업하기](http://sujinlee.me/professional-github/), [오픈소스 입문을 위한 아주 구체적인 가이드](https://velog.io/@ppp3195/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-%EC%9E%85%EB%AC%B8%EC%9D%84-%EC%9C%84%ED%95%9C-%EC%95%84%EC%A3%BC-%EA%B5%AC%EC%B2%B4%EC%A0%81%EC%9D%B8-%EA%B0%80%EC%9D%B4%EB%93%9C) - 두 개의 글 다 너무 좋은 글 인것 같아 공유합니다. 참고해주세요.

## Issue 작성법
> 모든 이슈는 적어도 한가지 이상의 마크다운을 사용하여 작성해주세요. 
- **공부** - 본인이 공부한 내용 또는 공유하고 싶은 내용이 있다면 `study` 태그를 달아서 작성해주세요. 
플러그인에 대한 아이디어가 있다면 이곳에 먼저 자료를 공유해주셔도 좋습니다. 아이디어를 공유할때에는 이해할 수 있을만한 자료를 함께 첨부해주세요. 공유할만한 자료가 없다면 설명을 구구절절하게 해주셔도 됩니다.
- **회의** - 팀 별 온라인이나 오프라인 회의를 하시면 인증 사진과 함께 `meeting` 태그를 달아서 팀원 중 한 분이 작성해주세요.

## 플러그인 아이디어 고려 사항
- 될 수 있으면 글로벌 한 것이 좋습니다. 
- 많은 사람들이 좋아할만 한 것 or 플러터에서 불편했던것이 있다면 더더욱 좋겠네요 :)
- 컨트리뷰톤 기간 동안 개발 할 수 있는 정도의 난이도면 좋겠습니다. 만약 난이도가 높아도 본인이 그 분야를 잘 알고 리딩할 수 있다면 상관없습니다. 사실 이럴 경우 아주 Best 일 듯 싶어요. 만일 아주 쉬운 난이도의 플러그인이라면 빠르게 끝내고, 하나 더 만듭시다.
- 비슷한 플러그인이 있더라도 그 플러그인이 메인테인이 잘 안되거나 기능이 많이 부족하다면 다른 기능을 보충해서 더 완성도 높은 플러그인을 만드는것도 괜찮습니다. 

## 패키지와 플러그인의 차이
 - 패키지는 dart 언어로만으로도 개발 할 수 있는 라이브러리입니다.
주로 UI 적인 라이브러리들이 대개 dart 언어 만으로도 개발이 가능합니다.
플러터는 ReactNative 와는 다르게 bridge 를 사용하지 않고 플러터에서 개발한 위젯을 직접 화면에 그리기 때문에, 웬만한 UI 적인 것들은 dart 로만 개발이 가능합니다. (애니메이션, 위젯 등등..)

 - 플러그인은 Android, iOS 네이티브 코드를 사용하여 플러터에서 하나의 코드로 사용할 수 있게끔 만들어주는 것입니다. 주로 네이티브에 종속적인 API 를 사용하여 어떤 기능을 구현한다고 할 때 사용합니다. 저희가 만들어야 할 것들은  네이티브 코드가 들어간 플러그인이지만, 상황에 따라서 패키지를 만드셔도 좋습니다. (그러나 그럴려면 모든 팀원이 플러터를 해주셔야합니다. 👍 ) 

----

이것이 첫번째 가이드입니다. 발대식 잘 하시고 17일날 온라인 회의로 뵙겠습니다.
다들 열정이 넘치셔서 좋네요! 공식적으로 Required 한 것은 [Plugin 기초 example 따라하기] 하시고 에뮬레이터나 시뮬레이터 화면 캡쳐하여 이슈에 올리는것입니다! 나머지는 제가 위에 써놓은 것들 자유롭게 공부하시고 공부한것 공유도 해주시고 함께 논의도 해봅시다. 파이팅 !

이슈는 제가 주관적인 판단으로 `close` 하겠습니다. 질문이나 고민이 있다면 언제든 말씀해주세요!

**Comment by eungikim** [comment]
깃허브로 취업하기 저도 이글 보고 이메일부터 개인용과 개발자용을 완전히 분리했어요 정말 좋은글이에요
