### ISSUE TITLE
💡플러그인 아이디어 #4: Docking state detection

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter-moum#12]
도배성 이슈 죄송합니다 ㅠㅠ

현재 디바이스의 도킹 상태 (e.g. 책상, 자동차 등)를 알 수 있는 플러그인이 아직 없는거 같더라구요.
안드로이드는 [ACTION_DOCK_EVENT](https://developer.android.com/training/monitoring-device-state/docking-monitoring)로 알 수 있는데, ios는 잘 몰라서 여쭈어보니까.. 정확하지는 않지만 [EAAccessoryManager](https://developer.apple.com/documentation/externalaccessory/eaaccessorymanager)로 할 수 있지 않을까? 하시더라구요.

이것도 가능만 하다면 쉬운 구현일거같아요

**Comment by songyiYu** [comment]
도배성 이슈 좋습니다 👍
