### ISSUE TITLE
💡플러그인 아이디어 #5: Hardware buttons

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter-moum#13]
음? 의외로 디바이스의 볼륨 버튼이나 홈버튼, 전원 버튼, 혹은 이어폰의 버튼 클릭을 감지하는 기능이 플러터에 아직 없는거같더라구요.
비스무리한 파편들이 몇몇 플러그인들로 보이는거같기도한데 제대로된건 없는거같고..

하드웨어 버튼 클릭을 감지하는 플러그인도 괜찮을거같아요

**Comment by songyiYu** [comment]
홈버튼 감지는 저도 필요한 기능이라 해봤는데 안드로이드는 api가 아니고 라이프사이클이랑 오버라이드 함수 조합해서 하는게 있더라구요. (이어폰 연결 감지하고 버튼 클릭은 평강님이랑 따로 만들고 있었는데..)이 플러그인이 잘 개발된다면 정말 유용한 플러그인이 될 것 같네요 :) 파편화 되어 있는 플러그인을 하나로 합치는것도 좋은 방법이에요!
