### ISSUE TITLE
🦕React native 의 라이브러리중에서 찾아보면 좋은게 나올 수 도 있을것같아요

### ISSUE THREAD

**Issue by eungikim** [flutter-moum/flutter-moum#15]
조금 릴리즈 시간이 지난 리액트 네이티브에서 아이템을  얻을 수 있을것같아요.
필요하다고 만들어진 하드웨어 부분의 라이브러리 중 플로터에 추가가 안된게 있나 찾아봐야겠어요

**Comment by minsub0922** [comment]
오 좋은 생각인 것 같습니다 ! 좀 막막 했었는데 한번 찾아볼게요 :)

**Comment by songyiYu** [comment]
헉 제가 이 얘기를 빠트렸었군요!!! 😭맞아요 RN 참고하는것 아주 좋은 방법입니다!
