### ISSUE TITLE
🦕플레이스토어, 앱스토어 열기

### ISSUE THREAD

**Issue by eungikim** [flutter-moum/flutter-moum#16]
검색을 해보다가 각 환경에 맞는  스토어 화면을 열어주는거 소소하고 좋지 않을까 생각했는데

https://pub.dev/packages/launch_review

여기에 있네요.

하지만 버전을 보면 나와있는데 2018년 3월, 2019년 3월 이렇게 띄엄띄엄 있네요.
같은걸 개발해봐도 될까요? 정말 쉬워보이는데?

**Comment by songyiYu** [comment]
안그래도 화상회의때 하려고 했던 플러그인이에요 ㅋㅋㅋ 통했네요. 저희 앱에서도 사용하고 있는데 이 플러그인이 안좋은게 무조건 리뷰쓰는 페이지로만 열려요! 그래서 앱 페이지로 열리는거 만들면 좋을것 같아요 :)
