### ISSUE TITLE
🦕스토어에 올라가있는 최신 버전 확인

### ISSUE THREAD

**Issue by eungikim** [flutter-moum/flutter-moum#17]
각 스토어에 올라가있는 최신 버전을 확인해보는걸 만들어보면 어떨까요?
아래 글에선
https://medium.com/@naumanahmed19/prompt-update-app-dialog-in-flutter-application-4fe7a18f47f2

1. 패키지 인포로 자기 앱 버전 확인하고
2. firebase config 로 원격으로 앱의 설정을 바꿔 업데이트 팝업 띄워주고
3. url_launch 로 각 스토어 실행한다
(자세히 읽지는 않았습니다)

android 에서는 편법으로 paly store html 파싱해서 버전관련 부분을 확인합니다.
ios 는 json 파싱하는것같고요

이부분을 개발해보면 어떨까요

**Comment by songyiYu** [comment]
요것도 유용하게 쓰일것 같네요 👍
