### ISSUE TITLE
[플러그인 아이디어] 폰 다이얼띄우기

### ISSUE THREAD

**Issue by minsub0922** [flutter-moum/flutter-moum#19]
안드의 ACTION_CAll / ACTION_DIAL 이나 iOS의 application.open(callURL) 처럼

버튼이나 텍스트 클릭시 바로 전화걸기  나 다이얼 찍히는 상태로 넘어가는 라이브러리가 없어보입니다~

**Comment by songyiYu** [comment]
오 몰랐던 부분이네요~!

**Comment by giantsol** [comment]
요고 저도 궁금해서 찾아봤었는데 url_launcher라는 플러그인 써서 할 수 있긴 한거 같더라구요!
https://stackoverflow.com/a/43150873 여기서 봤어요 ㅋㅋㅋ
