### ISSUE TITLE
[플로터 스터디]: Future 메소드 👏

### ISSUE THREAD

**Issue by chokyungjin** [flutter-moum/flutter-moum#20]
## 2번째 이슈
> 컨트리뷰톤이 끝난 이후에도 스스로 플로터에 대해서 공부하고 싶은데 혹시 좋은 자료나 사이트 있으시면 공유해주시면 감사드리겠습니다!!
------

![img](https://t1.daumcdn.net/cfile/tistory/99D7A0355B91EA4728)

## Future , async 키워드 

플러그인 예제를 보면서 처음보는 키워드가 있었는데 *Future*였다. 비동기 프로그래밍을 위한 키워드라고 하는데 Future<T>를 리턴 타입으로 설정하여 Future가 필요한 메소드 등에서 사용한다. 응답 성공시 json.decode로 응답의 body를 JSON으로 만들고 Post 클래스에서 만든 fromJson 메소드로 초기화한다.

```dart
  // Get battery level.
  String _batteryLevel = 'Unknown battery level.';

  Future<void> _getBatteryLevel() async {
    String batteryLevel;
    try {
      final int result = await platform.invokeMethod('getBatteryLevel');
      batteryLevel = 'Battery level at $result % .';
    } on PlatformException catch (e) {
      batteryLevel = "Failed to get battery level: '${e.message}'.";
    }

    setState(() {
      _batteryLevel = batteryLevel;
    });
  }
```

[출처: 플러그인예제](https://flutter.dev/docs/development/platform-integration/platform-channels#example-calling-platform-specific-ios-and-android-code-using-platform-channels)

[출처: 플러터-flutter-앱-만들기 ]( https://medium.com/@changjoopark/플러터-flutter-앱-만들기-블로그-글-상세-dc1ba68d4cef)

------

> 다트 홈페이지에서도 친절하게 Future, async, await 키워드에 대해서 설명해준다!

- future는 Future의 인스턴스 중 하나이다.
- future는 함수의 비동기 작동이 완료되거나 throw error를 기다리고 있다. 
- 비동기 처리가 끝나면 future는 값을 가지고 완료한다. 반대의 경우는 에러를 가지고 끝낸다. 

------
## Example

```dart
Future<void> getUserOrder() {
  // Imagine that this function is fetching user info from another service or database
  return Future.delayed(Duration(seconds: 3), () => print('Large Latte'));
}

main() {
  getUserOrder();
  print('Fetching user order...');
}
```

getUserOrder()가 main의 print()보다 먼저 실행되더라도 출력값은 정상적인 순서대로 나온다. 이유는 'Large Latte'가 출력되기 전에 딜레이를 받았기 때문!!

------

## 요약

- Future<T> 인스턴스는 제네릭으로 받을 수 있다.
- future가 리턴 값 없으면 , Future<void>.
- future는 완료하거나 완료하지 않거나 두가지 상태이다.
- future를 리턴하는 함수 호출할 때, 그 함수는 끝내야 하는 일들을 큐에 넣고 완료되지 않은 future를 리턴한다.
- future연산이 끝날 때, future는 값이나 에러를 가지고 끝낸다.

[출처: Dart async-await](https://dart.dev/codelabs/async-await)

**Comment by songyiYu** [comment]
플러터를 계속 공부하고 싶으시다면 Udemy에서 Angela 강의 좋아요 ! (그러나 유료..) 유튜브 영상은 유튜버 코딩파파 라는 분이 올리는 컨텐츠 있는데 그것도 아주아주 좋습니다 !!

**Comment by songyiYu** [comment]
그리고 구글 플러터팀이 올리는 유튜브 영상도 아주아주 좋으니 추천해드립니당 ! 
https://www.youtube.com/watch?v=wE7khGHVkYY&feature=youtu.be
요 시리즈에요
