### ISSUE TITLE
2019-09-17 #1플러터모움 회의 

### ISSUE THREAD

**Issue by kwanguuuu** [flutter-moum/flutter-moum#21]
# 2019-09-17 화상회의

## 회의 정보
- 일시 : 2019-09-17 21:30 ~ 22:30
- 방식 : 온라인 화상회의 ( 구글 행아웃 )
- 참석 : 유송이, 최평강, 조경진, 채문영, 최민섭, 김병규, 양어진, 김광유, 이한솔, 조준영, 김은기
- 불참 : 유광우(개인사정)

## 회의목적
1. 플러그인 조사 발표
2. 기타 공유사항 전달

### 조경진
- **OCR 부분** 점수가 낮아 다뤄봤으면
	- OCR(Optical character recognition): 인쇄되거나 손을 쓴 문자, 기호, 마크등을 컴퓨터가 인식할 수 있게 바꾸는 것을 말한다
- 애니메이션, UI부분

### 채문영
- 구글 API중 없는 플러그인 만들어보기
- 화면 자동변경 플러그인: 화면가로/세로 여부에 따라서 동영상&사진 등 가로세로 모드 변경(해상도)
	- 플러터에서 기본으로 해주는 것 같은데 확인은 필요(유송이)

### 최민섭
- 이슈에 올린 다이얼 부분 <https://github.com/flutter-moum/flutter-moum/issues/19>
	- [url_launcher](https://pub.dev/packages/url_launcher)에서 잘 해주고 있는것 같음 (이한솔)

### 김병규
- 스크린샷 콜백 함수 호출 플러그인
	- 스크린샷(캡쳐)시, 스크린샷 블록(안보이게 하기): 안드로이드는 있음, 아이폰은 없음 
	- 콜백함수 호출로 메세지 등 전달: 안드로이드 아이폰 둘다 있음
- 앱 종료 이벤트
	- 비정상 종료 했을 때 실행 되는 함수들 (터미네이트 관련)

### 양어진
- GPS정보를 한글로 변환하는 플러그인

### 김광유
- 헬스킷

### 이한솔
- 비행기모드 탐지
- 바로가기 아이콘  (안드로이드 전용)
- 실시간 날짜 변경 감지
- 디바이스 하드웨어 버튼 감지
- 이어폰 플러그인/아웃 감지
- 이미지 컨트롤 위젯

### 조준영
- 와이파이 연결여부 감지
- 알림센터 같은 위젯 (아이폰 메뉴 제일 왼쪽으로 넘기면 나오는 것)
	- 안드로이드는 foreground로 만들어본 사례 [포그라운드 관련 API](https://developer.android.com/guide/components/services?hl=ko)
	- 아이폰 위젯 만드는 건 어렵지 않아요 (누구?)

### 최평강
- 위젯
- 게임센터 (ios 게임센터 등록 등) / 구글플레이 연동 플러그인

### 유송이
- 스크린락 감지 플러그인
- 스크린 전체 감지 플러그인(밝기조절, 꺼짐 방지, 스크린락 감지 등)을 통합한 플러그인
- 앱 스토어 열어주는 플러그인 ( 현재 리뷰 쓰는 창으로 바로 연결 하는건 있음.?)
- push 권한을 크고 켤 수 있는 플러그인

### 김은기
- 스토어 최신버전 확인하는 플러그인 <https://github.com/flutter-moum/flutter-moum/issues/17>
	- 앱 버전/ 앱스토어 상 버전정보 비교
- 플레이스토어/ 앱스토어 열기 <https://github.com/flutter-moum/flutter-moum/issues/16>

## 기타 정보
- 패키지 검색
	- 패키지 검색 시, 기본은 높은 점수부터 순서로 나옴 -> **sort 시 newest**로 보면, 도움이 될 수 있으니 참조
- 패키지 점수관련
	- 48점(최저-시작점수), 80점 이상 (잘 관리된 것, 쓸만한 것), 90점이상 (대박)
- 투표해서 결정해보자 (플러그인 조사 한 것 중 투표)

## 차후 회의
- 일시: 2019-09-22 일 16:30
- 방식: 오프라인 (장소 미정)
- 불참예정: 김은기, 김병규, ? - 화상으로 참석 가능하면 참석
- 목표: ?

**Comment by songyiYu** [comment]
불참예정 ? 는 민섭님 ㅋㅋㅋㅋ

**Comment by eungikim** [comment]
### 조준영
* 와이파이 연결여부 감지 
https://pub.dev/packages/connectivity 여기서 데이터, 와이파이 연결 여부와 스트림을 구독하여 변경상태를 감지할 수 있습니다. 플러터 팀이 관리하고 있습니다

### 유송이
* push 권한을 크고 켤 수 있는 플러그인
(안드로이드) 이게 가능한건가요? 그냥 앱 정보 창으로 이동만 시켜줄 수 있지 않나요?
