### ISSUE TITLE
🦕안드로이드 암시적 인텐트 리시버

### ISSUE THREAD

**Issue by eungikim** [flutter-moum/flutter-moum#22]
안드로이드에서는 브로드캐스트 리시버라는 디바이스 이벤트를 감지하고 통지하는 컴포넌트가 있습니다. 앱에서 이를 감지하여 특정 이벤트를 캐치할 수 있습니다.

하지만 오레오(api26) 에서 디바이스 이벤트는 아래 허용 목록 제외하고 전부 불가합니다.
> https://developer.android.com/guide/components/broadcast-exceptions

이 허용 목록에서 쓸만한걸 플러터 플러그인으로 만들 수 있지 않을까 합니다.

* ACTION_BOOT_COMPLETED : 기기가 파워 온이 되면 한번 실행됩니다.
* ACTION_LOCALE_CHANGED : 기기의 위치 변경(국가?)
* ACTION_USB_ACCESSORY_ATTACHED, ACTION_USB_ACCESSORY_DETACHED,
ACTION_USB_DEVICE_ATTACHED, ACTION_USB_DEVICE_DETACHED : USB 연결 이벤트
* LOGIN_ACCOUNTS_CHANGED_ACTION : 계정 변경, AccountManager 관련
* ACTION_DEVICE_OWNER_CHANGED : 기기 주인 변경(기기 구글 로그인? 잘모르겠음)

**Comment by songyiYu** [comment]
이런것에 관한 플러그인이 없나요? 없다면 아주 좋은 소재네요 :)
