### ISSUE TITLE
스크린샷 콜백 관련 스터디 ( 안드로이드 MediaProjection 관련 )

### ISSUE THREAD

**Issue by kwanguuuu** [flutter-moum/flutter-moum#24]
## 1.스터디 목적

스크린샷 콜백 플러그인 개발 전에, 안드로이드 부분 지식이 필요해서
개인 스터디내용 기록 입니다!
저녁에 커밋을 따로 못할 것 같아 해당 커밋으로 대체합니다 .🤣🤣🤣
+ 관련 클래스 예제는 시간되면 연습해볼게요~

---
스크린샷 콜백관련 프로세스가
스크린샷 이벤트 발생 -> 안드로이드에서 감지 -> 콜백 전달  이라고 생각해서,
스크린샷 이벤트를 구글 검색해서 찾아보니 아래 내용들이 있어서 공부해봤습니다...

- 참조 URL

[https://stackoverflow.com/questions/13484516/ios-detection-of-screenshot](https://stackoverflow.com/questions/13484516/ios-detection-of-screenshot)
[https://developer.apple.com/documentation/uikit/uiapplication](https://developer.apple.com/documentation/uikit/uiapplication)

### MediaProjection
화면의 데이터를 가져오거나 음성 데이터 등을 가져오기 위한 API 
- capture screen contents
- record System audio

### MediaProjectionManager

- MediaProjectionManager를 통해서 screen capture session 실행 할 수 있음.
- audio는 불가능

### MediaProjectionManager의 메소드
```java
    //1. VirtualDisplay - 스크린 캡쳐를 위한 VirtualDisplay를 생성함
    VirtualDisplay createVitualDisplay(String name, int width, int height, int dpi, int flags,
				Suface surface, VirtualDisplay.Callback callback, Handler handler)
    
    //2. registerCallback - MediaProjection 상태가 변경될 때 알림을 받을 리스너 등록을 위한 메소드
    void registerCallback(MediaProjection.Callback collback, Handler, handler)
    
    //3. Stop - 프로젝션 스톱
    void stop()
    
    //4. unregisterCallback - 미디어 프로젝션 리스너 등록 해제
    void unregisterCallback(Mediaprojection.Callback callback)**
```
---
### 메소드 Parameter상세 설명

**1.createVirtualDisplay** → 스크린 컨텐츠 캡쳐를 위해 vd생성

- name(String) : vitualdisplay 이름, null안됨 (필수 파라미터)
- width(int) : 가로 (0 보다 커야 함)
- height(int) : 세로 (0 보다 커야 함)
- dpi(int) : density (0 보다 커야 함)
- flags(int) : 플래그 값 - 밑의 문자열을 상수로 받아서 처리
    - VIRTUAL_DISPLAY_FLAG_PUBLIC
    - VIRTUAL_DISPLAY_FLAG_PRESENTATION
    - VIRTUAL_DISPLAY_FLAG_SECURE
    - VIRTUAL_DISPLAY_FLAG_OWN_CONTENT_ONLY
    - VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR
- surface(Surface): virtual display가 렌더딩된 것. null로 하면 됨( 쟈동 )
- callback(VirtualDisplay.Callback) : vd 상태가 변경됬을 때 부르는 함수. maybe null
- handler(Handler): 콜백 실행될 시 콜백 제어.

**2.registerCallback** → MidiaProjection 변화를 감지할 리스너 등록

- callback
- handler

**3.stop** → projection 멈춤

**4.unregisterCallback** → 리스너 해제

**Comment by songyiYu** [comment]
아주 훌륭하네요 👍

**Comment by kwanguuuu** [comment]
참조 url이 잘못 되어 있어서 !

[MediaProjection | Android Developers](https://developer.android.com/reference/android/media/projection/MediaProjection.html)

[안드로이드 화면 캡쳐 API - MediaProjection 사용해보기 |](https://thdev.tech/androiddev/2016/04/09/Android-MediaProjection-Exmple/)
