### ISSUE TITLE
2019-09-22 #2 meeting

### ISSUE THREAD

**Issue by kwanguuuu** [flutter-moum/flutter-moum#25]
## 2019-09-23 플러터 모임

참석 : 유송이 조경진 유광우 이한솔 김광유 + 최평강(먹으러) 

---

### 활동내용

멘토님 생각으론 모여서 각자 플러그인 개발 끝내려고 했는데, 

4개 팀중 모두 참석한 팀이 없었고, 기존 선정한 플러그인 이미 개발된 것이 있어

플러그인 아이데이션을 주로 했습니다.

**락스크린 감지 플러그인 -** 한진 ( 이한솔, 양어진)

- 기존에 하기로 한것 락스크린 인데, 범위를 높여서 **하드웨어버튼 감지로 모두 늘림**

**스토어 최신버전 플러그인** - 김준우 (김은기, 조준영, 유광우)

- 스토어 최신버전 플러그인 만들기로 했는데, **업그레이더**(플러그인 명)가 넘 잘 되어있음.🤬🔥🔥
- **다른 플러그인으로 재선정 필요**
- 수요일 팀원 회의하기로함

**스토어 오픈 플러그인** - 문진 ( 채문영, 조경진)

- 스토어 오픈도 현재 되어있어서, 스터디 차원으로 스토어 오픈 해보기로 했다?

**스크린샷 콜백 플러그인** - 김민유 ( 김병규, 최민섭, 김광유)

- ..?
- 이번주에 회의 해요

---

### 기타 전달사항

1. 테스트 시, 네이티브 (IOS,Android) 먼저 하고 플러터 플러그인 연동 하는게 정확하고 편하다 ( 평강 )
2. 각 플러그인 팀 마다 package 명 정해서 레포 만들어요
3. 공식 회의는 3회 남음
- ~~9월1일 (오프)~~
- ~~9월17일(온라인)~~
- ~~9월22일(오프)~~
- 10월1일(온라인)
- 10월6일(오프)
- 10월 15일(온라인)

공식 회의 말고 팀별로 회의 등의 시간이 필요해 보입니다

---

### 기타 플러그인 아이데이션 나왔던 얘기

- QR코드  촬영 시, 플래시 달려 있는게 없음. → 플래시만 붙여주면 어떨까
- 포그라운드 노티피케이션.
- 위젯
- 전체화면 기능 .? ( 버튼 누르면 전체화면으로 변경)
- 위도/경도 ←>한글변환
    - 구글 geocoding. → 광우님 팀원들이랑 수요일에 회의.

**Comment by minsub0922** [comment]
정리 최고입니닷 ㅎ
