### ISSUE TITLE
2019-09-27 #1 문진팀 회의

### ISSUE THREAD

**Issue by moonyoungCHAE** [flutter-moum/flutter-moum#28]
2019-09-28 문진팀 (채문영/조경진) 회의
---

<h3>App store 열기 플러그인 진행 상황</h3>

* Android 완료  
* iOS 기능 구현 완료, Git Push하기   
* READ ME 작성하기  
* Interface 수정하기  

---
<h3> 앞으로의 계획 </h3>

* <b> 비행기 모드 탐지 플러그인 </b>  
지난 아이디어 중 한솔님이 제안하신 비행기 모드 탐지 플러그인을 만들어볼까 합니다.  
찾아보니 코드가 간단해서 되도록 빨리 만들어서 플러그인 올려보는 것이 목적입니다.  
후에 시간이 남으면 다른 팀에 참여하거나 다른 플러그인을 만들거나 고민 중!

**Comment by songyiYu** [comment]
벌써 다음 플러그인을 계획하다니 멋져요!
