### ISSUE TITLE
2019-10-01 #2 TEAM SIM meeting

### ISSUE THREAD

**Issue by eungikim** [flutter-moum/flutter-moum#29]
## 2019-10-01 팀 심 모임 
참석 : 유광유 조준영 김은기

---

### 활동내용
개발 목표, 스케쥴 설정

### 결정사항
- 기능
iOS  5가지  SIM info
Android 5가지 iOS 와 같은 메서드(추후 다른기능 추가)

- 마감일
10월 6일 일요일

- 중요한 꾸미기👩‍🏫
README - 김은기
TEST - 각자
EXAMPLE - 유광우
API doc - 조준영(wiki 생각중)

### 다음 스케쥴
10월 6일 선릉역에 만나 점심먹고 개발 마무리
개발 마무리 후 바로 다음 오픈소스 회의 들어가니까 아이디어 생각해오기

**Comment by eungikim** [comment]
추가 URL
https://github.com/react-native-webrtc/react-native-carrier-info
https://github.com/RandyWei/flt_telephony_info

**Comment by songyiYu** [comment]
Good!!
