### ISSUE TITLE
2019-10-01 #3 Online Meeting

### ISSUE THREAD

**Issue by songyiYu** [flutter-moum/flutter-moum#30]
# 10월 01일 4th 전체 회의 (온라인)
<img width="1602" alt="스크린샷 2019-10-01 오후 9 40 17" src="https://user-images.githubusercontent.com/9947963/65969344-960edc00-e49f-11e9-81de-27768217b3c5.png">

회의 방법 : 온라인 (행아웃)
회의 참여자 : 유송이, 조경진, 조준영, 김은기, 유광우 영상, 김광유, 최민섭, 김병규, 양어진, 이한솔
시간 : 오후 9시 30 ~ 오후 10시 

## Usim 팀

> 이번주 일요일 일찍 만나서 마무리 완성하기로 하였습니다.

- Trouble shooting - Android와  iOS 가 제공하는 유심 정보가 매우 달라 어려웠고, 맞춰가면서 진행
- 이번주 회의 참석 광우, 은기님 일찍 오심, 준영님 조금 늦음 (이르면 12시 30분)
- 코스랩 회의실 예약 필요

## Screenshot callback 팀
>깃이 터졌어요

- Trouble shooting - 모두 각자 Fork 하여 풀 리퀘스트를 날리다가 완전히 꼬여버린 상황. 따라서 Master 브랜치에 작업하기로 함.

*덧붙임말 - 시간 될 때 꼬인거 한 번 해결해 보시면 좋은 경험이 될 거에요!*

- 네이티브 스크린샷 콜백 코드는 작성 완료됨
- 내일쯤 완성 될 예정
- 이번주 회의 참석 - 광유, 민섭님 / 불참 - 병규님

## Hardware button 팀
> 진행했던것은 한솔이가, 진행할거는 어진이가 발표

- 네이티브 볼륨 업 다운 감지 구현은 진도가 느려서 만나서 작업
- 조언 : ios 버튼 감지는 애플의 리젝 사유가 될 수 있는데 어떡하죠 -> 플러그인 배포에는 문제 없으니 해당 플러그인을 사용하는 사용자의 재량에 맡겨야 할 것 같아요. 생각보다 이 기능에 대한 수요가 많을것 같습니다. 좋은 레퍼런스가 있으니 ios 도 함께 구현 해서 올려 보아요 

## Open Store 팀
> 배포 했어요!

- open appstore 배포 완료 
  [배포된건 요기서 확인!](https://pub.dev/packages/open_appstore)
- 깜빡 잠이든 문영님ㅠㅠ
- 두번째 플러그인 개발 중
- 점수 올리기 위한 작업 중!

## 기타 전달 사항
- 미니 해커톤 계획 -> 투표로 올릴게요
- 10월 19일날 마무리 모임 해요

**Comment by giantsol** [comment]
![image](https://user-images.githubusercontent.com/4879766/65979261-f3128e00-e4af-11e9-894d-bf5d50734f31.png)

볼륨 업 다운 감지 구현은 됐고 그 다음꺼때문에 그런거거든요!
그냥 그렇다구요..

**Comment by eungikim** [comment]
회의 때 했던 말이 들어가니까 현장감이 더 살아나네요!

**Comment by eojine** [comment]
> ![image](https://user-images.githubusercontent.com/4879766/65979261-f3128e00-e4af-11e9-894d-bf5d50734f31.png)
> 
> 볼륨 업 다운 감지 구현은 됐고 그 다음꺼때문에 그런거거든요!
> 그냥 그렇다구요..

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
