### ISSUE TITLE
2019-10-09 플러그인 홍보하기

### ISSUE THREAD

**Issue by moonyoungCHAE** [flutter-moum/flutter-moum#32]
송이 멘토님의 지령대로 ~~주작~~ 홍보 댓글을 달았습니다.
질문 올라온 게 별로 없더라고요 아숩

https://stackoverflow.com/questions/49685112/flutter-open-appstore-playstore-url/58291892#58291892

2댓입니당,, 좋아요 눌러주세요 ㅎㅎㅎㅎ  👍

**Comment by songyiYu** [comment]
(원래 이렇게 홍보하는 겁니당 속닥속닥) 
좋은것 만들었으니 이런 꿀 플러그인을 !!!
어려움을 겪는 분들에게 알려드려야죵 히히
근데 스택 오버 플로우에 좋아요 누르고 싶어도 reputation 점수가 낮아서 안되네요 흑흑ㅠㅠ

**Comment by songyiYu** [comment]
스택오버플로우에 답변을 다는것도 저는 엄청난 컨트리뷰션이라고 생각합니다. 
굳이 Github 가 아니더라도,, 사실 개발 할때 가장 많이 쓰이는게 스택 오버 플로우잖아욧??
근데 저도 이제서야 처음으로 답글 달아보네요. ㅎㅎ
굳이 답글을 달아서 다른 사람들에게 해결책을 주는것도 사실 대단한 정성인것 같아요. 암튼 굿입니다 !
