### ISSUE TITLE
2019-10-15 #5 Online Meeting

### ISSUE THREAD

**Issue by kwanguuuu** [flutter-moum/flutter-moum#34]
# 2019-10-15 #5 Online Meeting

회의 방법 : 온라인 (행아웃)
회의 참여자 : 유송이, 조경진, 조준영, 김은기, 김광유, 김병규, 양어진, 채문영
시간 : 오후 9시 30 ~ 오후 10시 20

## 0. 팀별 진행상황 체크
모든팀이 개발했던 앱의 배포를 완료하고, 지난주엔 점수올리기 등 활동을 위해 했습니다.
활동 중 특별한 이슈사항은 없었던 것으로 파악됨.

## 1.피드백 내용 공유
컨트리뷰톤 협회에서 피드백 받은 내용을 회의 때 공유했습니다.

### 주요 피드백 내용
> 컨트리뷰톤으로 개발, 배포를 모든 팀이 했다는건 큰 성과지만. 과정의 **히스토리**가 부족하다. 😥

<br></br>
### 원인분석
1. 팀 별로 카카오톡으로 대화, 직접 만나서 진행 등으로 이슈를 그때그때 처리하고 기록을 하지 않았던 것이 영향이 있는것 같습니다.
2. PR을 보내 MERGE하는 방식보다, 팀별 개발을 해 master에 직접 commit 해서 기대했던 모습과는 조금 달랐다 .? 
      - #### *hardware_buttons 팀과 screenshot_callback 팀 비교해보면 될거 같아요!*
<br></br>
### 정리
피드백 내용은 조금 속상 하지만 😥 시작도 잘했으니 마무리도 잘 합시다!🔥🔥😡😡😄😄
>**수,목,금,토** 동안 해당 내용을 이슈에 업데이트 해주세요
- 개발하면서 어려움을 겪었던 것(환경설정, 에러, 테스트 등)
- 잘 안되는(?) 내용들 (e.g: 미래위기)
- 회의했을 때 토론했던 내용들. 개발 방법론 등
<br></br>
## 2. 위키 정리요청
<code>이슈-개발-배포</code> 과정을 <code>wiki 작성</code>해 <code>플러그인 개발 활동 내용을 공유</code>하면 좋은 자료가 될 것 같습니다!
- 위키 작성의 취지& 목적은[해당링크를 참조해주세요.](https://github.com/flutter-moum/flutter-moum/issues/33)
- 위키 템플릿은 [링크](https://github.com/flutter-moum/flutter-moum/wiki)입니다.

현재 템플릿은 6파트지만, 팀원이 10명이니 템플릿을 10명이 각각 작성할 수 있도록 멘토님이 정해주실거에요
템플릿 선정방법
- 선착순
- 랜덤순
<br></br>
## 3. 프로젝트 마무리 ;(
> 마지막으로 **<code>발표준비</code>** 해야합니다!!!!!

예전에 은기님이 말씀해주신 것 처럼 **기**-**승**-**전**-**결** 만들기로~
- 발표자: ~~한명 빼고 다 앎~~
- 발표내용:
	- <code>**기**</code> - 아이데이션 시작
		- 컨트리뷰톤 첫모임, 팀원 너낌 인상 인성 파악
        - 플러그인 개발 아이데이션(우리 팀 첫 온라인 화상회의 생각)
    <br></br>
	- <code>**승**</code> - 본격 활동
		- 팀 생성, 플러그인 개발 킥오프
        - 팀별 역할 구분, 중간중간 피드백 등 젤 활동적
    <br></br>
	- <code>**전**</code> - 개발 및 배포
		- 개발한 플러그인들을 배포함
        - 오 스타 받음, 오 포크 떠감, 오 점수 올라
        - 리드미 업뎃해라 등
    <br></br>
	- <code>**결**</code> - 컨트리뷰톤(플러터 모움) 소감 및 후기
		- 나의 활동은 무엇이었는가
		- 배포 하니 어떻니
		- 좋았던 점, 아쉬운 점
		- 앞으로 뭐할래 등

위와 같은 구조가 될것 같습니다.
<br></br>
## 4. 기타 회의중 피드백
> 우선 다들 고생하셨습니다!! 멋져요!!!
- 우리가 개발한 플러그인 말고, 다른 오픈소스 활동도 해봅시다! (pr 날리고, issue 작성해주고)
	- 개인적 생각으론 안드로이드 x마이그레이션 해주세요 계속 issue 날리거나 pr해줘도 좋을것 같아요 (like permission plugin)
- 플러터 아닌 분야더라도, 이 활동을 통해 오픈소스 컨트리뷰터로써 변한 면모가 있음 알려주세요
- 코드리뷰는 좀 부족했던것 같은데 남은시간 해봐도 좋을거 같아요
- ~~토요일은 고기먹기~~

**Comment by beygee** [comment]
정리왕!!

**Comment by songyiYu** [comment]
크으 기가 막히네여!!

**Comment by kwanguuuu** [comment]
@beygee 😁😁@songyiYu 이전 회의록 참고해서 작성해봤어요~ 문서 실력이 느는중

**Comment by eungikim** [comment]
감사합니다. 감사합니다. 감사합니다.
