### ISSUE TITLE
코드랩 google-photos-sharing 작성시 주의사항

### ISSUE THREAD

**Issue by eungikim** [flutter-moum/flutter-moum#35]
https://codelabs.developers.google.com/codelabs/google-photos-sharing

플로터 연습을 위해 코드랩을 가끔가다 하나씩 만들어봅니다. 위 코드랩은 구글 sign-in 과 포토 api 를 사용해서 사용자들 끼리 여행 사진을 공유하는 플로터 어플리케이션을 만드는 코드랩입니다.

구현을 따라가는 도중 google sign-in 에서 에러가 나서 진행이 안됩니다. 제 추측으로는 firebase 프로잭트와 gcp 프로잭트가 달라서 그런것같습니다. 그걸 맞추기 위해 권한까지 확인하고 이리저리 건드려봤지만 실패했네요.

과정중에 firebase 와 gcp 에서 photo api 사용 설정하는게 있네요. 코드랩에는 이렇게 되어있습니다.  
"파이어베이스에서 새로운 프로잭트를 생성하고....블라블라, 그 다음에는 Photo api 링크로 가서 사용하기를 선택하세요. 해당 버튼이 disable 되어있다면 좌상단의 스피너에서 프로젝트를 파이어베이스에서 만든 프로젝트를 선택하세요"

저는 대충 이미 있는 프로젝트들에서 기능만 추가해서 만들려고 했는데 에러가 나고 해결하려고 엄청 시간을 쏟아붙고도 잠을 못자고 있습니다. 다른분들은 위 코드랩을 만드시면 새로운 프로잭트를 꼭 만들기 바랍니다.

정말 프로잭트 관련 문제인가 해당 코드랩 깃헙에가서 이슈도 남겼습니다.
https://github.com/googlecodelabs/photos-sharing/issues/12

**Comment by songyiYu** [comment]
오 코드랩에서 플러터 해 볼 생각은 안해봤는데 ! 이슈 공유까지.. 좋은 정보 감사해요 굿!

**Comment by eungikim** [comment]
코드랩에 스크린샷이 잘못되어있는것같아서 이슈 하나 더 남겼습니다 ~_~
https://github.com/googlecodelabs/photos-sharing/issues/13

**Comment by songyiYu** [comment]
> 코드랩에 스크린샷이 잘못되어있는것같아서 이슈 하나 더 남겼습니다 ~_~
> [googlecodelabs/photos-sharing#13](https://github.com/googlecodelabs/photos-sharing/issues/13)

그러게요 google-service.json 저 파일 위치 되게 중요한데 스크린샷이 잘못 나와있군요
👍
