### ISSUE TITLE
첫 PR 날리기 (05/17 일요일)

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter-moum#40]
각자 플러터 레포에 첫 PR을 날려보고 5월 17일 저녁 9시에 공유!

**Comment by songyiYu** [comment]
easy-fix가 easy가 아닌거슬...

**Comment by giantsol** [comment]
#41 

저는 여기서 작업중입니다! 오리지널 이슈 링크를 달면 그 오리지널 이슈 페이지에서도 우리께 보이니까.. 오리지널 링크를 다는곳은 영어로 써야할듯
