### ISSUE TITLE
[7월 26일 일요일] 발대식

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter-moum#45]
- [x] 프로젝트 소개 및 운영방안 공유
- [x] 스터디 요일 정하기
- [x] 깃허브 멤버 초대
- [x] 깃 경험 수요조사
- [x] 사진 찍기
- [x] 번호 교환

**Comment by giantsol** [comment]
[Flutter Moum 발대식.pdf](https://github.com/flutter-moum/flutter-moum/files/4977542/Flutter.Moum.pdf)
[Flutter Moum 발대식.pptx](https://github.com/flutter-moum/flutter-moum/files/4977553/Flutter.Moum.pptx)

<p float="left">
  <img src="https://user-images.githubusercontent.com/4879766/88500189-f2c91d80-d002-11ea-888e-f5da1762aa8e.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/88500195-fa88c200-d002-11ea-9097-28447d47d0cd.jpeg" width=400 />
</p>

**Comment by giantsol** [comment]
**숙제🧚‍♂️**

**7월 31일 (금)에서 8월 1일 (토)로 넘어가는 자정까지** 아래 화면을 구현하고 안드로이드와 아이폰의 스샷을 **댓글**로 달아주세요!
물론, 아이콘과 글자크기, 글자색상 등은 맞추지 않아도 됩니다. 대강 레이아웃만 맞게 ㅎㅎ.
**코드는 첨부하지 않아도 됩니다.**

<img src="https://user-images.githubusercontent.com/4879766/88478592-a808c080-cf84-11ea-948d-e92c51f374eb.png" width="400" />
윗 사진 왼쪽 안드로이드, 오른쪽 아이폰

**(아이폰과 안드로이드의 버튼 수가 다르다는것도 구현해주세요!)**

**Comment by nero-angela** [comment]
## Homework
| android | ios |
| ---- | ---- |
| <img style="display: inline" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480662-2b7cde80-cf92-11ea-84c2-60923fd9ced7.gif"> | <img style="display: inline"  alt="logo" src="https://user-images.githubusercontent.com/26322627/88480663-2d46a200-cf92-11ea-88eb-0b009f4d50de.gif"> |

## ref
- 로고 이미지도 넣으실 분은 가져다 쓰세요!

| 열품타 | apple  | email | facebook | kakao | naver |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|<img style="display: inline" width="100" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480528-6894a100-cf91-11ea-906f-0123cb5e2395.png"> | <img style="display: inline" width="100" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480524-66324700-cf91-11ea-9d5c-bb3b75ace6b4.png"> | <img style="display: inline" width="100" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480525-67637400-cf91-11ea-9c64-1b6a2aba133e.png"> | <img style="display: inline" width="100" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480526-67fc0a80-cf91-11ea-8d90-a41b1b73b183.png"> | <img style="display: inline" width="100" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480527-67fc0a80-cf91-11ea-8b63-c7e2cff15361.png"> | <img style="display: inline" width="100" alt="logo" src="https://user-images.githubusercontent.com/26322627/88480529-69c5ce00-cf91-11ea-944a-f4e40f2e1733.png">|

**Comment by mkw8263** [comment]
| Android | iOS |
|------|-----|
| ![image](https://user-images.githubusercontent.com/20398201/88482893-2a9e7980-cf9f-11ea-975d-dbe152341b10.png) | ![image](https://user-images.githubusercontent.com/20398201/88482906-3db14980-cf9f-11ea-9415-b9ca2fe165c1.png) |

**Comment by gusghrlrl101** [comment]
| Android  | iOS  |
|---|---|
| ![image](https://user-images.githubusercontent.com/38372691/88483292-cfba5180-cfa1-11ea-9e29-7b5431d76e71.png) | ![image](https://user-images.githubusercontent.com/38372691/88483295-d8128c80-cfa1-11ea-8578-c64aa06e74fd.png)  |

**Comment by haeseoklee** [comment]
|아이오에스~|안드로이드~|
|---------|----|
|![스크린샷 2020-07-27 오전 3 47 50](https://user-images.githubusercontent.com/20268101/88486898-000ee980-cfbc-11ea-879c-329c2a459a49.png)|![스크린샷 2020-07-27 오전 3 47 56](https://user-images.githubusercontent.com/20268101/88486900-01401680-cfbc-11ea-8786-1263aaa9ae0c.png)|

**Comment by haeseoklee** [comment]
음주코딩...

**Comment by JuYeong0413** [comment]
| Android | iOS |
| -------- | --- |
<img src="https://user-images.githubusercontent.com/33684401/88532339-6852df00-d03f-11ea-8ecd-65d06b9c2cb1.png"> | <img src="https://user-images.githubusercontent.com/33684401/88532344-6b4dcf80-d03f-11ea-8138-355de4b9e2dd.png">

**Comment by jsh-me** [comment]
<img width="704" alt="flutter" src="https://user-images.githubusercontent.com/39688690/88545824-78c28400-d056-11ea-839c-f7a66f222edc.png">

**Comment by ChoiAhHyun** [comment]
|Android|iOS|
|---------|----|
|![Screenshot_1595997675](https://user-images.githubusercontent.com/35266591/88758213-debc2200-d1a2-11ea-80a3-81d0ebd87d21.png)|![KakaoTalk_20200729_104348518](https://user-images.githubusercontent.com/35266591/88758237-ebd91100-d1a2-11ea-87f8-c5f8478ea2e9.png)|

**Comment by younghwan** [comment]
Android  | IOS
------------- | -----------------
|<img width="431" alt="안드로이드" src="https://user-images.githubusercontent.com/45064909/88795483-0e871c00-d1db-11ea-8c88-e5e02ba2f22c.png">|<img width="433" alt="아이폰" src="https://user-images.githubusercontent.com/45064909/88795268-b819dd80-d1da-11ea-8c9b-859505926954.png">

**Comment by broccolism** [comment]
**[Android]**
![image](https://user-images.githubusercontent.com/45515332/88827058-6e45ed00-d204-11ea-9a91-7476e301764b.png) 
**[IOS]**
![image](https://user-images.githubusercontent.com/45515332/88886759-1d6edc80-d276-11ea-96ad-01c3a844224d.png)

**Comment by naraekn** [comment]
<img width="275" alt="스크린샷 2020-07-30 오후 7 07 56" src="https://user-images.githubusercontent.com/34229459/88910896-10fb7b80-d298-11ea-8624-e8f035ea088c.png">

<img width="304" alt="스크린샷 2020-07-30 오후 5 10 38" src="https://user-images.githubusercontent.com/34229459/88910919-18bb2000-d298-11ea-87e9-b5240cd31e74.png">

**Comment by parkwonhui** [comment]
<img width="268" alt="android_login" src="https://user-images.githubusercontent.com/44539705/88918135-edd6c900-d2a3-11ea-9238-40ba9168644d.png">

![iphon](https://user-images.githubusercontent.com/44539705/88918149-f5966d80-d2a3-11ea-9863-f4175e1ab5fb.png)

**Comment by ny927** [comment]
Android | iOS
------------ | -------------
![image](https://user-images.githubusercontent.com/32477115/88941075-892b6680-d2c3-11ea-82ae-838d584a56a1.png) | ![image](https://user-images.githubusercontent.com/32477115/88941404-ee7f5780-d2c3-11ea-82d8-75c5acad3bea.png)
