### ISSUE TITLE
[8월 1일 토요일] 첫 스터디

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter-moum#46]
주제:
- Flutter 이해하기
- Flutter Contribution 이해하기
- 숙제💁‍♂️

예상 시간: 1시간 30분 ~ 2시간

To Do:
- [x] 스터디 진행
- [x] 숙제 공지
- [x] 인증샷

**Comment by giantsol** [comment]
<p float="left">
  <img src="https://user-images.githubusercontent.com/4879766/89103270-89ef0480-d44b-11ea-858e-32ad1efed4f3.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89103275-91aea900-d44b-11ea-89b5-850c6ac44764.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89103278-94a99980-d44b-11ea-9af1-beb79027c0c7.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89103286-9d9a6b00-d44b-11ea-8c63-11a651fd20c2.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89103289-a0955b80-d44b-11ea-8b87-7b935fa9504b.jpeg" width=400 />
</p>

**Comment by giantsol** [comment]
<p float="left">
  <img src="https://user-images.githubusercontent.com/4879766/89103321-e5b98d80-d44b-11ea-9d5e-a2de5fd7c919.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89103326-e9e5ab00-d44b-11ea-9aa7-2fb838ab71a3.jpeg" width=400 />
</p>

**Comment by giantsol** [comment]
[FlutterMoum 스터디 01.pdf](https://github.com/flutter-moum/flutter-moum/files/5010645/FlutterMoum.01.pdf)

**Comment by giantsol** [comment]
👩‍🎓숙제👨‍🎓

(아마) **8월 7일 (금)에서 8월 8일 (토)로 넘어가는 자정**까지 아래 두가지를 해서 **댓글**로 달아주세요!

1. 관심있는 이슈 제목 1개 이상 (다른 분들이랑 겹쳐도 됩니다 ^_^) ☠️**주의**☠️ 이슈의 url은 달지 말아주세요!! 그냥 제목만 적어주세요! 저쪽 이슈에 저희 페이지 링크가 달립니다 ㅠ
2. 개발 환경 세팅하고 **tabs_test.dart** 파일을 연 화면 캡쳐하기

(예시)
<img width="300" alt="Screen Shot 2020-08-01 at 11 24 57 PM" src="https://user-images.githubusercontent.com/4879766/89103641-3b8f3500-d44e-11ea-876f-94aadf12dcf7.png">

**Comment by nero-angela** [comment]
### issue
- Padding inside Table #52248
- TextSpan could use Tooltip support #51587

### tabs_test.dart
<img alt="스크린샷 2020-08-01 오후 10 43 04" src="https://user-images.githubusercontent.com/26322627/89103696-b2c4c900-d44e-11ea-8e18-b2bf3b9859b0.png">

**Comment by JuYeong0413** [comment]
### Issue
- `https://github.com/flutter/flutter/issues/52005`
- `https://github.com/flutter/flutter/issues/32114` (PR open `https://github.com/flutter/flutter/pull/62728`)
- `https://github.com/flutter/flutter/issues/29999` (PR open `https://github.com/flutter/flutter/pull/62729`)
- `https://github.com/flutter/flutter/issues/10613`
- `https://github.com/flutter/flutter/issues/19954`
`https://github.com/flutter/flutter/pull/55489` 이 PR에서 다른 분이 해결해두셨는데 Breaking change여서 진행이 멈춰진 상태더라고요! 이어서 도전해보려고 합니다. 🙂 
### tabs_test.dart
<img width="622" alt="Screen Shot 2020-08-01 at 11 39 17 PM" src="https://user-images.githubusercontent.com/33684401/89103902-54004f00-d450-11ea-8fb6-de13ed0ef741.png">

**Comment by JuYeong0413** [comment]
### :bulb: Issue 고르는 작은 팁  
- `easy fix` 라벨 외에도 `good first contribution`, `entertaining new contributor project`라는 라벨도 있습니다!  
단점은 올라온 지 조금 오래된 이슈들이라는 것...?
- 이슈 목록을 보면 가끔 우측에 Pull Request가 링크된 이슈는 표시가 보여지는데, 
<img width="151" alt="Screen Shot 2020-08-02 at 3 07 02 AM" src="https://user-images.githubusercontent.com/33684401/89107622-460cf700-d46d-11ea-9be3-ee6f8372e394.png">

**이게 붙어있다고 다른 사람이 한 거라고 생각하면서 그냥 지나치면 괜찮은 이슈인데도 불구하고 놓치는 경우가 생길 수도 있어요!** 
Closed된 Pull Request가 있는 경우에도 저렇게 뜨더라고요. 제목 보고 괜찮아보인다 싶으면 들어가서 다른 사람이 open한 상태인 PR이 존재하는지 확인하시면 좋을 것 같아요.

**Comment by haeseoklee** [comment]
### Issue

1.  Add borderRadius to Table widget.
2.  NestedScrollView does not support SliverAppBar floating and snapping simultaneously
3.  Using NestedScrollView, TabBarView and AutomaticKeepAliveClientMixin will scroll other scroll views in the tab.

1번은 easy fix 태그가 있어서 먼저 시도해 볼려고합니다
2번 3번은 둘 다 NestedScrollView 문제로 연관되어있는듯 합니다. 실력이 된다면? 해결해보고 싶습니다.

### tabs_test.dart

![스크린샷 2020-08-02 오전 1 48 49](https://user-images.githubusercontent.com/20268101/89115811-88632200-d4c7-11ea-8fac-6fcff3d788dc.png)

**Comment by gusghrlrl101** [comment]
## 이슈
 
1. CupertinoNavigationBar leading is too high #18536

2. AppBar shows Back Button when EndDrawer is open #13601

## 개발 환경

![image](https://user-images.githubusercontent.com/38372691/89431292-ae641d00-d77a-11ea-9730-cbd9796217c0.png)

**Comment by mkw8263** [comment]
### 이슈 🔢 
1. `https://github.com/flutter/flutter/issues/48958` (FadeInImage() needs a ImageLoadingBuilde)
...(토요일까지 천천히 보면서 할만한 이슈들 보면서 추가할게요^^)

### 환경세팅 💻 
![image](https://user-images.githubusercontent.com/20398201/89432843-8ecdf400-d77c-11ea-902d-d4ee0f68da84.png)

**Comment by jsh-me** [comment]
## issue:
1. `https://github.com/flutter/flutter/issues/14399`
 - Make it easier to diagnose invisible text with unspecified text style #14399

2. `https://github.com/flutter/flutter/issues/61612`
- If I create an activity and use methodchannel, can flutter receive it? #61612

계속 추가하겠습니다~

## setting:
![image](https://user-images.githubusercontent.com/39688690/89432962-b1f8a380-d77c-11ea-85f1-45d8a3e666bd.png)

**Comment by ChoiAhHyun** [comment]
## 이슈

1. Codelab Building beautiful UIs with Flutter mistake on page 4 (Build the main user interface) #62228
2. Padding inside Table #52248

계속 찾아볼게요!

## 개발 환경
![20200805_012536](https://user-images.githubusercontent.com/35266591/89532345-9e0c7a80-d82c-11ea-85f2-23bc56df5625.png)

**Comment by naraekn** [comment]
이슈
---
* `https://github.com/flutter/flutter/issues/59540` (TextOverflow: add option to put the ellipsis in the center rather than end)
* `https://github.com/flutter/flutter/issues/49723` (Unexpectedly transparent container in web)

개발환경
---
<img width="662" alt="스크린샷 2020-08-06 오후 10 23 58" src="https://user-images.githubusercontent.com/34229459/89540332-da91a380-d837-11ea-9e02-e028a3bd1df3.png">

**Comment by ny927** [comment]
<h3>이슈</h3>
DropdownButton doesn't animate newly selected value #4378

Coloured Android navigation bar not working with Launch Screen #58579

<h3>개발 환경 세팅</h3>

<img width="828" alt="스크린샷 2020-08-06 오후 11 51 04" src="https://user-images.githubusercontent.com/32477115/89546843-fe58e780-d83f-11ea-9c31-73dfb4900d01.png">

**Comment by parkwonhui** [comment]
### 이슈
how does one change the border color of a checkbox #26961
Specify tab size in Text widget #50087

### 개발 환경
![2020-08-04 221846](https://user-images.githubusercontent.com/44539705/89553032-f56c1400-d847-11ea-8747-9ca82b26df87.jpg)

**Comment by younghwan** [comment]
## **이슈**
[Web] Key simulation does not work on web #61021
flutter download should not include .pub-cache #44062

## **개발환경**
<img width="709" alt="스크린샷 2020-08-07 오후 11 30 29" src="https://user-images.githubusercontent.com/45064909/89657682-67a42d80-d908-11ea-8324-854ec3928a62.png">

**Comment by broccolism** [comment]
죄송합니다 플러터에서 계속 에러가 나서 방금 막 셋팅 완료되었습니다.ㅠㅠ

### Issue
- Documentation for ListView constructor should warn about changing widget list #46922
- how does one change the border color of a checkbox #26961


### Flutter Environment
![image](https://user-images.githubusercontent.com/45515332/89664975-e9995400-d912-11ea-81e0-a0f2b7ce47c4.png)

그런데 다시 보니 tabs_test.dart 에서는 에러가 안 나는데
flutter_test/lib/src 아래에 있는 몇몇 파일에 빨간줄이 그이네요..ㅠ
금요일 내내 한솔님이 고쳐주셨는데 channel 바꾸고 하다보니 아직 뭔가 덜 된거같습니다 흑흑
