### ISSUE TITLE
[8월 8일 토요일] 두번째 스터디

### ISSUE THREAD

**Issue by songyiYu** [flutter-moum/flutter-moum#47]
주제:
- PR 날려보기 
- 실습
- SDK 환경설정

예상 시간 : 2시간

ToDo:
- [x] 스터디 진행
- [x] 이슈 선택
- [x] 인증샷

**Comment by songyiYu** [comment]
[PR날리기(2차스터디).pdf](https://github.com/flutter-moum/flutter-moum/files/5044823/2020ContributhonStudy2.pdf)

**Comment by giantsol** [comment]
이주영: `https://github.com/flutter/flutter/issues/52005`
임현호: `https://github.com/flutter/flutter/issues/13601`
손영인: `https://github.com/flutter/flutter/issues/46922`
민경운: `https://github.com/flutter/flutter/issues/48958`
박원희: `https://github.com/flutter/flutter/issues/62967`
정세희: `https://github.com/flutter/flutter/issues/42837`
김난: `https://github.com/flutter/flutter/issues/49723`
신영환: `https://github.com/flutter/flutter/issues/62737`
이찬호: `https://github.com/flutter/flutter/issues/52248`
김나연: Sample code - SizeTransition
이해석: `https://github.com/flutter/flutter/issues/24048`
최아현: `https://github.com/flutter/flutter/issues/14399`

**Comment by giantsol** [comment]
<p float="left">
  <img src="https://user-images.githubusercontent.com/4879766/89711899-296e4300-d9c8-11ea-8ae7-e8c211fc6ee1.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89711900-2bd09d00-d9c8-11ea-9235-c8c4b6aababa.jpeg" width=400 />
  <img src="https://user-images.githubusercontent.com/4879766/89711903-2ecb8d80-d9c8-11ea-993d-973a72686a11.jpeg" width=400 />
</p>
