### ISSUE TITLE
💡플러그인 아이디어 #1: Airplane mode detection

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter-moum#9]
역시 웬만한 플러그인들은 이미 다 나와있는거같아요 ㅋㅋㅋ
그래서 단순히 끄적이면서 생각하는걸로는 역부적일거같고..
제가 지금 연구해보고 있는 방식은 안드로이드에 어떤 [시스템 서비스](https://developer.android.com/reference/android/content/Context.html#getSystemService(java.lang.String))들이 있었는지, 어떤 [intent](https://developer.android.com/reference/android/content/Intent.html#constants_2) 종류가 있었는지 등 땅굴을 파보고 있는데 아직 비행기 모드에 관한 플러그인은 없는거 같더라구요.
안드로이드에서는 구현이 매우 쉬울텐데 ios는 어쩔지 모르겠네요.
떠올라서 이슈 남겨봐요!

**Comment by giantsol** [comment]
(숙제부터 해야하는데..)

**Comment by songyiYu** [comment]
비행모드 간단하고 좋아보이네요!!
